---@meta

EVENT_ADD_ON_LOADED = 1
EVENT_PLAYER_ACTIVATED = 2
EVENT_RAID_TRIAL_STARTED = 3
EVENT_BOSSES_CHANGED = 4
EVENT_UNIT_DEATH_STATE_CHANGED = 5
EVENT_BROADCAST = 6
EVENT_DISPLAY_ALERT = 7
EVENT_DISPLAY_ANNOUNCEMENT = 8
EVENT_CHAT_MESSAGE_CHANNEL = 9
EVENT_RAID_TRIAL_SCORE_UPDATE = 10
EVENT_COMBAT_EVENT = 11

CHAT_CHANNEL_MONSTER_EMOTE = 1
CHAT_CHANNEL_MONSTER_SAY = 2
CHAT_CHANNEL_MONSTER_WHISPER = 3
CHAT_CHANNEL_MONSTER_YELL = 4

ACTION_RESULT_DIED = 1

---@type DUNGEON_DIFFICULTY
DUNGEON_DIFFICULTY_NONE = 0
---@type DUNGEON_DIFFICULTY
DUNGEON_DIFFICULTY_NORMAL = 1
---@type DUNGEON_DIFFICULTY
DUNGEON_DIFFICULTY_VETERAN = 2
--- @alias DUNGEON_DIFFICULTY
--- |`DUNGEON_DIFFICULTY_NONE` # No difficulty setting, e.g. overland zones
--- |`DUNGEON_DIFFICULTY_NORMAL` # Normal instance (dungeon, trial, arena)
--- |`DUNGEON_DIFFICULTY_VETERAN` # Veteran instance (dungeon, trial, arena)

LibAddonMenu2 = {}




LEFT = 1
RIGHT = 2
TOP = 3
BOTTOM = 4
TOPLEFT = 5
TOPRIGHT = 6
BOTTOMLEFT = 7
BOTTOMRIGHT = 8
CENTER = 9

MAX_BOSSES = 8

---@type Control
---@diagnostic disable-next-line: assign-type-mismatch
GuiRoot = {}

SLASH_COMMANDS = {}

TIME_FORMAT_STYLE_COLONS = 1
TIME_FORMAT_PRECISION_TENTHS = 2